# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=512)),
                ('answer', models.CharField(max_length=128)),
                ('comment', models.TextField(max_length=512, null=True)),
                ('grade', models.IntegerField(choices=[(0, 'easy'), (1, 'normal'), (2, 'hard'), (3, 'unfair')], default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_game.Category')),
            ],
        ),
    ]
