# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(choices=[(0, 'easy'), (1, 'normal'), (2, 'hard'), (3, 'unfair'), (4, 'tricky')], default=0),
        ),
    ]
